name: 'Hello World'
description: 'Hello World from Rust-generated WebAssembly!'
inputs:
  actor:
    description: 'The user that triggered the workflow'
    default: ${{ github.actor }}
  command:
    description: 'The command to run'
    required: true
  toolchain:
    description: 'The toolchain to install e.g. nightly'
    required: false
  components:
    description: 'The components to install e.g. rustc'
    required: false
  profile:
    description: 'A profile that selects components (minimal, default, complete)'
    required: false
  targets:
    description: 'Targets to install e.g. x86_64-unknown-linux-gnu'
    required: false
  default:
    description: 'Whether this toolchain should be set as the default'
    required: false
outputs:
  result:
    description: 'The result of the action execution'
runs:
  using: 'node16'
  main: 'dist/index.js'
