name: CI
on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3.0.11
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Build and run tests
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build
      - run: npm run test

      # Test the action
      - id: hw
        uses: ./
        with:
          command: install-rustup
          toolchain: nightly
          profile: minimal
          targets: wasm32-unknown-unknown
          default: true

      - if: steps.hw.outputs.result != 'success'
        run: exit 1
