name: CI
on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3.0.11
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Build and run tests
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
      - run: npm run test

      # Test the action
      - id: install-rustup
        uses: ./
        with:
          command: toolchain
          toolchain: nightly
          profile: minimal
          targets: wasm32-unknown-unknown
          components: clippy
          default: true
      - id: cargo-build
        uses: ./
        with:
          command: cargo build
          args: --target=wasm32-unknown-unknown
      - id: cargo-clippy
        uses: ./
        with:
          command: cargo clippy
      - run: find ~/.cache
      - run: find ~/.local
      - if: steps.cargo-build.outputs.result != 'success'
        run: exit 1
