name: CI
on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3.0.11
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Build and run tests
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
      - run: npm run test

      # Test the action
      #
      - id: restore-cargo-cache
        uses: ./
        with:
          command: cache
          cache-only: indices crates git-repos
          min-recache-indices: 1h
      - id: install-toolchain
        uses: ./
        with:
          command: install-rustup
          toolchain: nightly
          profile: minimal
          targets: wasm32-unknown-unknown
          components: clippy
          default: true
      - id: install-grcov
        uses: ./
        with:
          command: cargo install
          args: grcov
      - id: cargo-build
        uses: ./
        with:
          command: cargo build
          args: --target=wasm32-unknown-unknown
          use-cross: true
      - id: cargo-clippy
        uses: ./
        with:
          command: cargo clippy
      - run: find ~/.cache
      - run: find ~/.local
      - run: rustc --version
      - if: steps.cargo-build.outputs.result != 'success'
        run: exit 1
